-- Rustic Rose Productions - Supabase/PostgreSQL schema and migrated data
-- Run this entire file once in Supabase SQL Editor.
-- Generated from the uploaded MySQL dump.

BEGIN;

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'Admin' CHECK (role IN ('Super Admin','Admin','Staff')),
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  last_login_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name VARCHAR(150) NOT NULL,
  description TEXT NULL,
  duration_minutes INTEGER NULL CHECK (duration_minutes IS NULL OR duration_minutes >= 0),
  price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS availability (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_available SMALLINT NOT NULL DEFAULT 1 CHECK (is_available IN (0,1)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_day_hours UNIQUE(day_of_week,start_time,end_time)
);

CREATE TABLE IF NOT EXISTS blocked_dates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocked_date DATE NOT NULL UNIQUE,
  reason VARCHAR(255) NULL,
  created_by INTEGER NULL REFERENCES admins(id) ON DELETE SET NULL ON UPDATE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference VARCHAR(30) NOT NULL UNIQUE,
  service_id INTEGER NULL REFERENCES services(id) ON DELETE SET NULL ON UPDATE CASCADE,
  service VARCHAR(150) NOT NULL,
  event_date DATE NOT NULL,
  consultation_date DATE NULL,
  consultation_time TIME NULL,
  guest_count INTEGER NULL CHECK (guest_count IS NULL OR guest_count >= 0),
  budget VARCHAR(100) NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  notes TEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Confirmed','Completed','Cancelled')),
  admin_notes TEXT NULL,
  estimated_revenue NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  ip_address VARCHAR(45) NULL,
  user_agent TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id INTEGER NULL REFERENCES admins(id) ON DELETE SET NULL ON UPDATE CASCADE,
  action VARCHAR(100) NOT NULL,
  description TEXT NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  error_type VARCHAR(100) NULL,
  error_message TEXT NOT NULL,
  file_name VARCHAR(255) NULL,
  line_number INTEGER NULL,
  request_uri TEXT NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activity_admin ON activity_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_blocked_created_by ON blocked_dates(created_by);
CREATE INDEX IF NOT EXISTS idx_booking_service ON bookings(service_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_event_date ON bookings(event_date);
CREATE INDEX IF NOT EXISTS idx_customer_email ON bookings(email);
CREATE INDEX IF NOT EXISTS idx_customer_phone ON bookings(phone);
CREATE INDEX IF NOT EXISTS idx_error_created ON error_logs(created_at);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admins_updated_at ON admins;
CREATE TRIGGER trg_admins_updated_at BEFORE UPDATE ON admins FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_services_updated_at ON services;
CREATE TRIGGER trg_services_updated_at BEFORE UPDATE ON services FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_availability_updated_at ON availability;
CREATE TRIGGER trg_availability_updated_at BEFORE UPDATE ON availability FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_bookings_updated_at ON bookings;
CREATE TRIGGER trg_bookings_updated_at BEFORE UPDATE ON bookings FOR EACH ROW EXECUTE FUNCTION set_updated_at();


INSERT INTO "admins" ("id", "name", "username", "password", "role", "is_active", "last_login_at", "created_at", "updated_at") VALUES
(5, 'Surin Garrido', 'Surin', '$2y$10$RZmaJ4Xau6DfcaGhFRlZ4eJrRe.wGaGd.eEqic9e08J09LnNxyLlS', 'Admin', 1, NULL, '2026-08-07 01:32:00', '2026-08-07 01:32:00');


INSERT INTO "services" ("id", "service_name", "description", "duration_minutes", "price", "is_active", "created_at", "updated_at") VALUES
(1, 'Full-Service Wedding Planning', 'Complete wedding planning and coordination.', 60, '0.00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(3, 'Event Planning', 'Planning and coordination for private and corporate events.', 60, '0.00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(5, 'Venue Management', 'Professional venue and short-term rental management.', 60, '0.00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(6, 'Wedding Day Coordination', '', NULL, '0.00', 1, '2026-08-06 18:21:12', '2026-08-06 18:21:12');


INSERT INTO "availability" ("id", "day_of_week", "start_time", "end_time", "is_available", "created_at", "updated_at") VALUES
(1, 1, '09:00:00', '17:00:00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(2, 2, '09:00:00', '17:00:00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(3, 3, '09:00:00', '17:00:00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(4, 4, '09:00:00', '17:00:00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(5, 5, '09:00:00', '17:00:00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36'),
(6, 6, '09:00:00', '17:00:00', 1, '2026-08-06 17:44:36', '2026-08-06 17:44:36');


INSERT INTO "blocked_dates" ("id", "blocked_date", "reason", "created_by", "created_at") VALUES
(1, '2026-08-13', '', NULL, '2026-08-06 18:14:30'),
(2, '2026-08-08', '', NULL, '2026-08-06 18:15:12');


INSERT INTO "bookings" ("id", "booking_reference", "service_id", "service", "event_date", "consultation_date", "consultation_time", "guest_count", "budget", "first_name", "last_name", "email", "phone", "notes", "status", "admin_notes", "estimated_revenue", "ip_address", "user_agent", "created_at", "updated_at") VALUES
(5, 'RR-2026-A79A9ED8', NULL, 'Month-of Coordination', '2026-08-19', '2026-08-19', '00:00:00', 12121, '', 'Surin', 'Garrido', 'Surin@gmail.com', '01289181782817', 'de', 'Pending', '', '12121.00', '::1', NULL, '2026-08-07 01:08:59', '2026-08-07 01:41:58'),
(6, 'RR-2026-F954B5D6', NULL, 'Venue Management', '2026-08-22', '2026-08-22', '00:00:00', NULL, NULL, 'Chekoy', 'Garrido', 'garridosurin@gmail.com', '01289172817', 'I need it as soon as possible', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-07 03:14:17', '2026-08-07 03:14:17'),
(9, 'RR-2026-F6E4F8D1', NULL, 'Month-of Coordination', '2026-09-03', '2026-09-03', '00:00:00', 2117, NULL, 'Surin', 'Garrido', 'garridosurin@gmail.com', '19829182918982', '', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-10 01:58:12', '2026-08-10 01:58:12'),
(10, 'RR-2026-43F4CF55', NULL, 'Full Planning', '2026-08-13', '2026-08-13', '00:00:00', 10, NULL, 'tomboy', 'flores', 'tom@gmail.com', '36217829', 'hey', 'Completed', '', '0.00', '::1', NULL, '2026-08-10 01:59:40', '2026-08-10 15:08:14'),
(11, 'RR-2026-B998AF85', NULL, 'Partial Planning', '2026-08-12', '2026-08-12', '00:00:00', 122, '', 'Nano', 'yak', 'nano@gmail.com', '9874635167892', 'yes', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-11 03:01:11', '2026-08-11 03:01:11'),
(12, 'RR-2026-29ECE9D1', NULL, 'Full Planning', '2026-08-13', '2026-08-13', '00:00:00', 20, NULL, 'Surin', 'Garrido', 'garridosurin@gmail.com', '098767821', '', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-11 03:13:52', '2026-08-11 03:13:52'),
(13, 'RR-2026-D1F3ECCB', NULL, 'Venue Management', '2026-08-15', '2026-08-15', '00:00:00', 21, NULL, 'Ryan', 'Garrido', 'Garridoryan@gmail.com', '567289131', '', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-11 03:17:48', '2026-08-11 03:17:48'),
(14, 'RR-2026-BF2F2CD9', NULL, 'Elopement Package', '2026-08-12', '2026-08-12', '00:00:00', 12, NULL, 'Sin', 'Sinbad', 'sin@gmail.com', '563789212', 'NI', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-11 03:58:40', '2026-08-11 03:58:40'),
(15, 'RR-2026-8D1A1A87', NULL, 'Venue Management', '2026-08-12', '2026-08-12', '00:00:00', 21, NULL, 'Hatdog', 'HAS', 'hat@gmail.com', '426781902', '', 'Pending', NULL, '0.00', '::1', NULL, '2026-08-11 04:07:32', '2026-08-11 04:07:32');


INSERT INTO "activity_logs" ("id", "admin_id", "action", "description", "ip_address", "created_at") VALUES
(1, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-06 17:54:59'),
(2, NULL, 'login', 'Administrator signed in', '::1', '2026-08-06 17:55:27'),
(3, NULL, 'blocked_date_manage', 'Updated blocked dates', '::1', '2026-08-06 18:14:30'),
(4, NULL, 'blocked_date_manage', 'Updated blocked dates', '::1', '2026-08-06 18:15:12'),
(5, NULL, 'admin_create', 'Created admin Surin', '::1', '2026-08-06 18:17:23'),
(6, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-06 18:17:27'),
(7, NULL, 'login', 'Administrator signed in', '::1', '2026-08-06 18:17:34'),
(8, NULL, 'service_manage', 'Updated services', '::1', '2026-08-06 18:20:41'),
(9, NULL, 'service_manage', 'Updated services', '::1', '2026-08-06 18:21:12'),
(10, NULL, 'booking_update', 'Updated booking #1', '::1', '2026-08-06 18:28:38'),
(11, NULL, 'booking_update', 'Updated booking #3', '::1', '2026-08-06 18:29:54'),
(12, NULL, 'booking_update', 'Updated booking #3', '::1', '2026-08-06 18:33:50'),
(13, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-06 23:33:28'),
(14, NULL, 'login', 'Administrator signed in', '::1', '2026-08-06 23:33:36'),
(15, NULL, 'service_manage', 'Updated services', '::1', '2026-08-06 23:35:02'),
(16, NULL, 'booking_delete', 'Deleted booking RR-2026-98BA0BB1 (#4) from the booking list', '::1', '2026-08-06 23:36:25'),
(17, NULL, 'booking_delete', 'Deleted booking RR-2026-5C9DA91E (#2) from the booking list', '::1', '2026-08-06 23:37:35'),
(18, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-06 23:40:52'),
(19, NULL, 'login', 'Administrator signed in', '::1', '2026-08-06 23:41:03'),
(20, NULL, 'admin_delete', 'Deleted admin admin (#1)', '::1', '2026-08-06 23:41:15'),
(21, NULL, 'admin_create', 'Created admin Simon', '::1', '2026-08-06 23:44:12'),
(22, NULL, 'booking_update', 'Updated booking #1', '::1', '2026-08-06 23:46:46'),
(23, NULL, 'booking_delete', 'Deleted booking RR-2026-2491BD19 (#3)', '::1', '2026-08-07 00:22:16'),
(24, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-07 00:33:27'),
(25, NULL, 'login', 'Administrator signed in', '::1', '2026-08-07 00:34:46'),
(26, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-07 00:36:17'),
(27, NULL, 'login', 'Administrator signed in', '::1', '2026-08-07 00:37:30'),
(28, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-07 00:39:26'),
(29, NULL, 'login', 'Administrator signed in', '::1', '2026-08-07 00:59:18'),
(30, NULL, 'booking_update', 'Updated booking #1', '::1', '2026-08-07 01:01:15'),
(31, NULL, 'booking_delete', 'Deleted booking RR-2026-B5B2E976 (#1)', '::1', '2026-08-07 01:02:00'),
(32, NULL, 'login', 'Administrator signed in', '::1', '2026-08-07 01:30:56'),
(33, NULL, 'admin_delete', 'Deleted admin Surin (#2)', '::1', '2026-08-07 01:31:39'),
(34, NULL, 'admin_create', 'Created admin Surin', '::1', '2026-08-07 01:32:00'),
(35, NULL, 'logout', 'Administrator signed out', '::1', '2026-08-07 01:32:04'),
(36, 5, 'login', 'Administrator signed in', '::1', '2026-08-07 01:32:11'),
(37, 5, 'admin_delete', 'Deleted admin admin (#4)', '::1', '2026-08-07 01:35:00'),
(38, 5, 'admin_delete', 'Deleted admin Simon (#3)', '::1', '2026-08-07 01:35:03'),
(39, 5, 'booking_update', 'Updated booking #5', '::1', '2026-08-07 01:41:58'),
(40, 5, 'logout', 'Administrator signed out', '::1', '2026-08-07 01:44:32'),
(41, 5, 'login', 'Administrator signed in', '::1', '2026-08-07 01:46:30'),
(42, 5, 'logout', 'Administrator signed out', '::1', '2026-08-07 02:11:57'),
(43, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-07 02:53:29'),
(44, 5, 'booking_delete', 'Deleted booking RR-2026-9EA237FD (#7) from the booking list', '::1', '2026-08-07 03:39:31'),
(45, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-07 12:09:56'),
(46, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-07 12:13:44'),
(47, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-07 12:24:53'),
(48, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-07 15:56:23'),
(49, 5, 'booking_update', 'Updated booking #8', '::1', '2026-08-07 16:21:22'),
(50, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-08 10:33:53'),
(51, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-08 10:56:35'),
(52, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-08 11:00:46'),
(53, 5, 'login', 'Administrator signed in', '::1', '2026-08-08 13:04:12'),
(54, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-08 13:57:58'),
(55, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-08 15:44:17'),
(56, 5, 'booking_delete', 'Deleted booking RR-2026-ACC1F8DB (#8) from the booking list', '::1', '2026-08-08 15:54:44'),
(57, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-08 15:58:21'),
(58, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 01:56:50'),
(59, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 01:57:14'),
(60, 5, 'booking_update', 'Updated booking #10', '::1', '2026-08-10 02:00:59'),
(61, 5, 'logout', 'Administrator signed out', '::1', '2026-08-10 02:11:46'),
(62, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 04:35:53'),
(63, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 04:36:08'),
(64, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 04:49:14'),
(65, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 04:56:53'),
(66, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 11:23:23'),
(67, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 12:29:16'),
(68, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 14:20:59'),
(69, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 14:21:27'),
(70, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 14:25:12'),
(71, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-10 15:07:35'),
(72, 5, 'booking_update', 'Updated booking #10', '::1', '2026-08-10 15:08:14'),
(73, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-11 02:35:20'),
(74, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-11 02:37:22'),
(75, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-11 02:59:53'),
(76, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-11 04:07:44'),
(77, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-12 00:33:50'),
(78, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-12 01:40:50'),
(79, 5, 'login', 'Administrator signed in from frontend popup', '::1', '2026-08-13 10:56:46');


-- Advance identity sequences after importing explicit IDs.
SELECT setval(pg_get_serial_sequence('admins','id'), COALESCE((SELECT MAX(id) FROM admins),1), true);
SELECT setval(pg_get_serial_sequence('services','id'), COALESCE((SELECT MAX(id) FROM services),1), true);
SELECT setval(pg_get_serial_sequence('availability','id'), COALESCE((SELECT MAX(id) FROM availability),1), true);
SELECT setval(pg_get_serial_sequence('blocked_dates','id'), COALESCE((SELECT MAX(id) FROM blocked_dates),1), true);
SELECT setval(pg_get_serial_sequence('bookings','id'), COALESCE((SELECT MAX(id) FROM bookings),1), true);
SELECT setval(pg_get_serial_sequence('activity_logs','id'), COALESCE((SELECT MAX(id) FROM activity_logs),1), true);
SELECT setval(pg_get_serial_sequence('error_logs','id'), COALESCE((SELECT MAX(id) FROM error_logs),1), true);

COMMIT;
